name: Data Platform CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check SQL files exist
        run: |
          ls -la sql
          test -f sql/create_table.sql

      - name: Validate SQL syntax basic check
        run: |
          grep -i "CREATE TABLE" sql/create_table.sql

  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform -chdir=terraform/dev init

      - name: Terraform validate
        run: terraform -chdir=terraform/dev validate
      
      - name: Run tfsec security scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/dev
      
      - name: Terraform plan
        run: terraform -chdir=terraform/dev plan

      - name: Terraform apply
        run: terraform -chdir=terraform/dev apply -auto-approve